apiVersion: v2
name: terraform-operator
version: 0.0.7
appVersion: 0.1.0
description: a kubernetes controller to manage terraform workflows
engine: gotpl
keywords:
  - terraform-operator
  - terraform-kubernetes
  - terraform-run
  - terraform-workflows
  - terraform-controller
  - terraform
  - kubernetes
sources:
  - https://github.com/kube-champ/terraform-operator