apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "terraform-operator.fullname" . }}
  labels:
  {{- include "terraform-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "terraform-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "terraform-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io