apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terraform-operator.fullname" . }}
  labels:
    {{- include "terraform-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - configmaps
    - secrets
    - pods
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups: ["batch"]
  resources:
    - jobs
  verbs:
    - get
    - create
    - delete
    - list
    - watch
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - rolebindings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - run.terraform-operator.io
  resources:
  - terraforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-runner
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]