apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "terraform-operator.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terraform-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "terraform-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terraform-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "terraform-operator.serviceAccountName" . }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}

      imagePullSecrets: {{ include "terraform-operator.imagePullSecrets" . | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "terraform-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          securityContext:
            readOnlyRootFilesystem: true
          
          ports:
            - name:  metrics
              containerPort: 8080
              protocol: TCP

          env:
            - name: DOCKER_REGISTRY
              value: {{ include "terraform-runner.imageRegistry" . }}
            - name: TERRAFORM_RUNNER_IMAGE
              value: {{ .Values.terraformRunner.image.repository }}
            - name: TERRAFORM_RUNNER_IMAGE_TAG
              value: {{ .Values.terraformRunner.image.tag }}
            - name: KNOWN_HOSTS_CONFIGMAP_NAME
              value: {{ template "terraform-operator.fullname" . }}-known-hosts