{{ if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "terraform-operator.fullname" . }}-metrics
  labels:
    {{- include "terraform-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.metrics.service.annotations }}
    {{- toYaml .Values.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{- if (or (eq .Values.metrics.service.type "LoadBalancer") (eq .Values.metrics.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.metrics.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if .Values.metrics.service.clusterIP }}
  clusterIP: {{ .Values.metrics.service.clusterIP }}
  {{ end }}
  {{ if eq .Values.metrics.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.metrics.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.metrics.service.type "LoadBalancer") (not (empty .Values.metrics.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.ports.http }}
      targetPort: metrics
      protocol: TCP
      {{- if (and (or (eq .Values.metrics.service.type "NodePort") (eq .Values.metrics.service.type "LoadBalancer")) (not (empty .Values.metrics.service.nodePorts.http))) }}
      nodePort: {{ .Values.metrics.service.nodePorts.http }}
      {{- else if eq .Values.metrics.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "terraform-operator.selectorLabels" . | nindent 4 }}
{{- end }}