{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "terraform-operator.name" . }}
    chart: {{ template "terraform-operator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: {{ template "terraform-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-runner
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "terraform-operator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}